### ISSUE TITLE
Not going to "my subscriptions"

### ISSUE THREAD

**Issue by Kiskis1** [Mattie432/YouTweak#13]
Basically when I go to youtube through a new tab then it redirects me, but after i watch a video and click that "YouTube" button in the top left corner it doesnt redirect me.. never..

**Comment by Mattie432** [comment]
Hi, I would suspect that YouTube is changing the layout of some of their pages and as such my extension no longer points to the correct icon to change the link. This has not taken effect on my youtube so I cannot test locally. If you could provide some information so that I can proactively change my extension to help others in this situation I would be very appreciative.

Please get the site to a state where clicking the button _does not_ take you to the expected page. In chrome:
1. Right Click the icon
2. Inspect Element
3. Developer tools window should appear.
4. Hover over the code in this window and you will notice things become highlighted on the main page.
5. Move up the code, hovering over the items, until the entire of the the top bar is highlighted (like this 
![image](https://cloud.githubusercontent.com/assets/3811007/10469055/92fb07a8-71fa-11e5-8685-692edf32bd6e.png)
 )
6. Right click that item
7. Edit as html
8. Copy the entire code in the box that shows up.
9. Paste as a comment here.

**Comment by Mattie432** [comment]
I have received a copy of the new YouTube homepage from another use and the icon in the top left has not changed. My extension should still be able to alter the destination of this link so I am unsure why you are experiencing this issue. Unfortunately If you cannot send me a copy of the page I will be unable to fix the issue. Please take a look at [capturing all of a page](https://github.com/Mattie432/YouTweak/wiki/Sending-a-copy-of-the-webpage-for-debugging#capture-all-of-the-page) to easily send me a copy of your webpage. Thanks.

**Comment by Kiskis1** [comment]
Sorry, still new to this git thing and haven't checked my email. Here is the page where clicking the home button does not redirect me. 
http://www36.zippyshare.com/v/BYPY2snr/file.html

**Comment by Mattie432** [comment]
No worries, thanks for taking the time to do that. It looks like the button is the same as usual, I suspect that this will be due to YouTube loading a new page (video) and my extension not realising the page has changed. Not sure how I can fix this at the moment but i am looking into it! There should be a new release sometime soon and hopefully I will have this fixed for then.

**Comment by Mattie432** [comment]
Hi again, would you be able to install the attached `testing` build in chrome using these [instructions](https://github.com/Mattie432/YouTweak/wiki/installing-a-developer-build) and check if a popup box displays when you re-create the issue. Thanks.

**Comment by Mattie432** [comment]
Closing as no response for a while & likely fixed here 22fb0c7738217dd449d12dd5a7a749b560926a4b
